name: Deploy Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/zaaac-admin/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        working-directory: backend
        run: mvn -B -DskipTests clean install

      - name: Prepare artifact
        run: cp backend/zaaac-admin/target/zaaac-admin.jar ./zaaac-admin.jar

      - name: Upload JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "zaaac-admin.jar"
          target: "${{ secrets.BACKEND_DIR }}"
          overwrite: true

      - name: Restart backend via screen
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            bash /home/ZacBlog/scripts/restart_backend.sh \
              "${{ secrets.BACKEND_DIR }}" \
              "${{ secrets.BACKEND_SCREEN }}" \
              "${{ secrets.JAVA_BIN || 'java' }}" \
              "${{ secrets.BACKEND_JAR_NAME }}"

            echo "=== screen sessions ==="
            screen -list || true
            echo "=== last 60 lines of app.log ==="
            tail -n 60 "${{ secrets.BACKEND_DIR }}/app.log" || true
